### ISSUE TITLE
Error in the resetting of the size parameter by the encoding function. 

### ISSUE THREAD

**Issue by ConstantJoe** [Lora-net/CTB#1]
Hello,

I have noticed that in some situations (though I have not managed to fully narrow down where), the encoding and decoding of frames can end up setting the packet size to -1. This appears to be a known issue since there is a workaround in proxy.py which re-encodes the packet to retrieve the correct packet size when this occurs (line 272 for uplink and 315 for downlink).

However, the packet size returned is a float, and this value gets set as the size parameter in the json. For the Things Stack, the size parameter is expected to be an integer, and so this causes the reception of all of these packets on the server to fail (for Chirpstack, from what I have seen, this is not an issue). To fix this, the size parameter returned from the encoder and decoder should explicitly be an integer i.e. the return statements for _encode_join_ and _encode_data_ in _lib_packet.py_ should be 

`return base64.b64encode(bytes.fromhex(mhdr + encrypted)).decode(), len(mhdr + encrypted) // 2`

instead of 

`return base64.b64encode(bytes.fromhex(mhdr + encrypted)).decode(), len(mhdr + encrypted) / 2`

and 

`return base64.b64encode(bytes.fromhex(phy_payload)).decode(), len(phy_payload) // 2`

instead of 

`return base64.b64encode(bytes.fromhex(phy_payload)).decode(), len(phy_payload) / 2`

respectively.

**Comment by Damgabino** [comment]
Hello,

This encode issue was solved in the newest version of the CTB (v1.1.0).
