### ISSUE TITLE
How to add an entry to the regionSKU table

### ISSUE THREAD

**Issue by ConstantJoe** [Lora-net/CTB#2]
Hello,

I see with the recent update that a new table has been added for additional parameters related to the region, _regionSKU_.

However, I do not see how to add an entry to this table. There is no way of adding to it through the web interface, and no obvious API call (IP/regionSKU, IP/table/regionSKU, IP/SKU etc) works. Could you let me know what is the correct format to add to this table?

**Comment by Damgabino** [comment]
Hello,

There is pending documentation to upload explaining with more detail the features and usage of the new version, meanwhile, to add a device with the region SKU parameter, you need to upload a json file to the CTB database using this command:

curl -X POST -H "Content-Type:text/plain" -d @device.json http://IP/device  
    
This in an example of a "device.json" file body:
[
  {
    "DevEui": "0000000000000000",
    "AppKey": "00000000000000000000000000000000",
    "NwkKey": "00000000000000000000000000000000",
    "region": "US"
  }
]

**Comment by iBrick** [comment]
Hi, @Damgabino. Your answer doesn't help, because to add device you need to add Region first to the table. Is this planned documentation update can be found somewhere?

**Comment by WisangAnggoro** [comment]
I agreed with @iBrick, is there any updated documentation about this project?

**Comment by sda3422** [comment]
@ConstantJoe , @iBrick and @WisangAnggoro , did you receive any help on this topic please ? I am facing the same issue of course... Thanks.

**Comment by iBrick** [comment]
> @ConstantJoe , @iBrick and @WisangAnggoro , did you receive any help on this topic please ? I am facing the same issue of course... Thanks.

Nope
